[package]
name = "ispwned-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto="0.2.36"
num_cpus="1.13.1"
chrono="0.4.19"
chrono-humanize="0.2.1"
keepass="0.4.9"